# Generated by Django 4.0.4 on 2022-06-03 14:52

import basics.validators
from django.db import migrations, models
import django.db.models.deletion
import foods.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost', models.CharField(max_length=100, null=True, validators=[basics.validators.rate_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('article_number', models.CharField(max_length=20, unique=True, validators=[foods.validators.article_number_validator])),
                ('cost', models.DecimalField(decimal_places=3, max_digits=11)),
                ('amount', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.amountunit')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.currency')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=11)),
                ('cost', models.CharField(max_length=100, validators=[basics.validators.rate_validator])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foods.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='foods.recipe')),
            ],
            options={
                'verbose_name': 'combinations',
            },
        ),
        migrations.AddConstraint(
            model_name='combination',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='recipe_ingredient_combination'),
        ),
    ]
